# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(324, 242)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.recTab = QtWidgets.QWidget()
        self.recTab.setObjectName("recTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.recTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addRecBtn = QtWidgets.QPushButton(parent=self.recTab)
        self.addRecBtn.setObjectName("addRecBtn")
        self.verticalLayout.addWidget(self.addRecBtn)
        self.runningRecLabel = QtWidgets.QLabel(parent=self.recTab)
        self.runningRecLabel.setObjectName("runningRecLabel")
        self.verticalLayout.addWidget(self.runningRecLabel)
        self.runningRecList = QtWidgets.QListWidget(parent=self.recTab)
        self.runningRecList.setObjectName("runningRecList")
        self.verticalLayout.addWidget(self.runningRecList)
        self.stopRecBtn = QtWidgets.QPushButton(parent=self.recTab)
        self.stopRecBtn.setObjectName("stopRecBtn")
        self.verticalLayout.addWidget(self.stopRecBtn)
        self.tabWidget.addTab(self.recTab, "")
        self.graphTab = QtWidgets.QWidget()
        self.graphTab.setObjectName("graphTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.graphTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.showGraphBtn = QtWidgets.QPushButton(parent=self.graphTab)
        self.showGraphBtn.setObjectName("showGraphBtn")
        self.verticalLayout_2.addWidget(self.showGraphBtn)
        self.separateCheckBox = QtWidgets.QCheckBox(parent=self.graphTab)
        self.separateCheckBox.setChecked(True)
        self.separateCheckBox.setObjectName("separateCheckBox")
        self.verticalLayout_2.addWidget(self.separateCheckBox)
        spacerItem = QtWidgets.QSpacerItem(20, 63, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.changeColoursBtn = QtWidgets.QPushButton(parent=self.graphTab)
        self.changeColoursBtn.setObjectName("changeColoursBtn")
        self.verticalLayout_2.addWidget(self.changeColoursBtn)
        self.tabWidget.addTab(self.graphTab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Broadband Bug"))
        self.addRecBtn.setStatusTip(_translate("MainWindow", "Start a recorder"))
        self.addRecBtn.setText(_translate("MainWindow", "Add recorder..."))
        self.runningRecLabel.setText(_translate("MainWindow", "Running recorders:"))
        self.stopRecBtn.setStatusTip(_translate("MainWindow", "Stop the recorder selected from the list"))
        self.stopRecBtn.setText(_translate("MainWindow", "Stop selected recorder..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.recTab), _translate("MainWindow", "Recorders"))
        self.showGraphBtn.setStatusTip(_translate("MainWindow", "Open a window showing the graph"))
        self.showGraphBtn.setText(_translate("MainWindow", "Show graph..."))
        self.separateCheckBox.setStatusTip(_translate("MainWindow", "Plot data from different methods as separate lines"))
        self.separateCheckBox.setText(_translate("MainWindow", "Separate data by method (recommended)"))
        self.changeColoursBtn.setStatusTip(_translate("MainWindow", "Change the colours of the graph lines"))
        self.changeColoursBtn.setText(_translate("MainWindow", "Change graph colours..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.graphTab), _translate("MainWindow", "Graph"))
